/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello.world;

public class App {
    public String getGreeting() {
        return "Hello, This is a demo Gradle-Project";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
